import { LivraisonType } from './livraison.model';

export const Livraions: LivraisonType[] = [
  {
    id_livraison: '1',
    livreur: undefined,
    commande: 'Ordinateur Apple Inc.',
    adresse: '123 Rue Principale',
    details: 'Laisser à la porte',
  },
  {
    id_livraison: '2',
    livreur: undefined,
    commande: 'Chaussures Nike Inc.',
    adresse: '456 Avenue du Chêne',
    details: "Appeler à l'arrivée",
  },
  {
    id_livraison: '3',
    livreur: undefined,
    commande: 'Livre Kindle Amazon',
    adresse: '789 Rue du Sapin',
    details: 'Déposer dans la boîte aux lettres',
  },
  {
    id_livraison: '4',
    livreur: '2',
    commande: 'Casque Sony',
    adresse: '101 Boulevard du Lac',
    details: 'Remettre en main propre',
  },
  {
    id_livraison: '5',
    livreur: undefined,
    commande: 'Console PlayStation',
    adresse: "321 Rue de l'Orme",
    details: "Sonner à l'interphone",
  },
  {
    id_livraison: '6',
    livreur: '3',
    commande: 'Tablette Samsung',
    adresse: "654 Boulevard de l'Érable",
    details: 'Code portail : 1234',
  },
  {
    id_livraison: '7',
    livreur: '3',
    commande: 'Téléphone Xiaomi Inc.',
    adresse: '987 Chemin du Cèdre',
    details: "Livrer à l'accueil",
  },
  {
    id_livraison: '8',
    livreur: undefined,
    commande: 'Montre Garmin',
    adresse: '555 Route du Soleil',
    details: 'Laisser chez le voisin',
  },
  {
    id_livraison: '9',
    livreur: undefined,
    commande: 'Vélo Trek',
    adresse: '777 Avenue des Platanes',
    details: 'Appeler avant de livrer',
  },
  {
    id_livraison: '10',
    livreur: undefined,
    commande: 'Sac à dos North Face',
    adresse: '888 Rue de la Montagne',
    details: 'Déposer sous le porche',
  },
  {
    id_livraison: '11',
    livreur: '2',
    commande: 'Écouteurs Bose',
    adresse: '999 Rue de la Forêt',
    details: 'Laisser à la réception',
  },
  {
    id_livraison: '12',
    livreur: undefined,
    commande: 'Livre Harry Potter',
    adresse: '123 Chemin du Ruisseau',
    details: 'Mettre dans la boîte aux lettres',
  },
  {
    id_livraison: '13',
    livreur: '3',
    commande: 'PC Portable Lenovo',
    adresse: '234 Boulevard du Centre',
    details: "Ne pas sonner, appeler à l'arrivée",
  },
  {
    id_livraison: '14',
    livreur: undefined,
    commande: 'Chaussures Puma',
    adresse: '345 Rue de la Gare',
    details: 'Remettre en main propre',
  },
  {
    id_livraison: '15',
    livreur: '2',
    commande: 'Smartphone OnePlus',
    adresse: '456 Route du Nord',
    details: 'Code portail : 5678',
  },
  {
    id_livraison: '16',
    livreur: undefined,
    commande: 'Clavier mécanique Logitech',
    adresse: '567 Allée des Pins',
    details: 'Déposer devant la porte',
  },
  {
    id_livraison: '17',
    livreur: undefined,
    commande: 'Lampe Philips Hue',
    adresse: '678 Boulevard du Midi',
    details: 'Laisser avec le concierge',
  },
  {
    id_livraison: '18',
    livreur: undefined,
    commande: 'Boîte de chocolat',
    adresse: '789 Avenue de la Mer',
    details: 'Sonner deux fois',
  },
  {
    id_livraison: '19',
    livreur: '3',
    commande: 'Guitare Fender',
    adresse: '890 Rue des Musiciens',
    details: 'Laisser à la porte du garage',
  },
  {
    id_livraison: '20',
    livreur: undefined,
    commande: 'Sac de sport Adidas',
    adresse: '901 Chemin du Stade',
    details: "Appeler avant d'entrer",
  },
];
