import { LivraisonType } from './livraison.model';

export const Livraions: LivraisonType[] = [
  {
    id_livraison: '1',
    livreur: undefined,
    commande: 'Ordinateur Apple Inc.',
    adresse: '12 Rue de la République, Grenoble, 38000',
    details: 'Laisser à la porte',
    delivered: false,
    deliveryDate: new Date('2025-02-06'),
  },
  {
    id_livraison: '2',
    livreur: '1',
    commande: 'Chaussures Nike Inc.',
    adresse: '32 Avenue Jean Perrot, Grenoble, 38100',
    details: "Appeler à l'arrivée",
    delivered: false,
    deliveryDate: new Date('2025-02-06'),
  },
  {
    id_livraison: '3',
    livreur: '2',
    commande: 'Livre Kindle Amazon',
    adresse: '54 Rue Saint-Jacques, Grenoble, 38000',
    details: 'Déposer dans la boîte aux lettres',
    delivered: false,
    deliveryDate: new Date('2025-02-06'),
  },
  {
    id_livraison: '4',
    livreur: undefined,
    commande: 'Casque Sony',
    adresse: '75 Rue du Drac, Grenoble, 38100',
    details: 'Remettre en main propre',
    delivered: false,
    deliveryDate: new Date('2025-02-06'),
  },
  {
    id_livraison: '5',
    livreur: '1',
    commande: 'Console PlayStation',
    adresse: '98 Avenue de Verdun, Grenoble, 38000',
    details: "Sonner à l'interphone",
    delivered: false,
    deliveryDate: new Date('2025-02-06'),
  },
  {
    id_livraison: '6',
    livreur: '2',
    commande: 'Tablette Samsung',
    adresse: '101 Boulevard de la Croix-Rousse, Grenoble, 38000',
    details: 'Code portail : 1234',
    delivered: false,
    deliveryDate: new Date('2025-02-06'),
  },
  {
    id_livraison: '7',
    livreur: '3',
    commande: 'Téléphone Xiaomi Inc.',
    adresse: '55 Rue de l’Alpe, Grenoble, 38100',
    details: "Livrer à l'accueil",
    delivered: false,
    deliveryDate: new Date('2025-02-06'),
  },
  {
    id_livraison: '8',
    livreur: undefined,
    commande: 'Montre Garmin',
    adresse: '120 Avenue Jean-Jaurès, Grenoble, 38000',
    details: 'Laisser chez le voisin',
    delivered: false,
    deliveryDate: new Date('2025-02-06'),
  }
];
